//
//  daysjs.tsx
//  AtSight version 1.0.0
//
//  Created by Nathan Quême on the 01/06/22 - 06/07/22.
//


import React from 'react'
import LocalizedStrings from 'react-native-localization'


/**
  en:{
    bread:"bread",
    butter:"butter",
    question:"I'd like {0} and {1}, or just {0}"
  }

   strings.formatString(strings.question, strings.bread, strings.butter)

   gives "I'd like bread and butter, or just bread"

*/
const localization = new LocalizedStrings({
  "en": {
    pdf: "PDF",
    value: "Value",
    description: "Description",
    search: "Search",
    next: "Next",
    cancel: "Cancel",
    close: "Close",
    edit: "Edit",
    send: "Send",
    confirm: "Confirm",
    ok: "OK",
    delete: "Delete",
    continue: "Continue",
    select: "Select",
    done: "Done",
    call: "Call",
    send_email: "Send email",
    see_more: "see more",
    translating: "Translating...",
    show_original: "Show original",
    show_translation: "Show translation",
    translate_text: "Translate text",
    edit_the_other_language: "Edit the other language",
    edit_the_x_other_language: "Edit the {0} other languages",

    no_internet_connection: "No internet connection",
    profile_not_found: "Profile not found",
    copied_to_clipboard: "Copied to clipboard",
    successfully_sent: "Successfully sent",

    street_address: "Street address",
    city: "City",
    country: "Country",
    code: "Code",
    change_email_address: "Change email address",
    email_address: "Email address",
    name: "Name",
    password: "Password",
    phone_number: "Phone number",
    creating_your_account_can_take_30_seconds: "Creating your account may take up to 30 seconds.",
    username: "Username",
    description_optional: "Description (optional)",

    email_address_successfully_updated: "Email address successfully updated.",
    phone_number_successfully_updated: "Phone number successfully updated.",
    changing_username_will_change_qr_warning: "Changing your username will change your QR code. Therefore, if you have placed QR codes in your establishment, you will need to update all of them.",
    select_language: "Select language",
    write_text: "Write text.",
    see_how_translation_works: "See how translation works.",
    manage_features_you_want_to_add_to_your_profile_descriptive_text: "Select the additional features you want to offer.",

    no_photo: "No photo",
    press_to_edit_photo: "Press to edit your account photo.",

    press_to_switch_pdf: "Press to switch PDF.",
    press_to_import_pdf: "Press to import PDF.",
    add_timetables: "Add timetables",

    no_menu_to_display: "There is no menu to display for the moment.",
    no_map_to_display: "There is no map to display for the moment.",

    terms: "Terms of Use",
    privacy: "Privacy policy",
    version: "Version",
    appleLanguageIndications: "To change the language in which text is displayed: \n1. Continue to the next screen.\n2. Tap Language to select the language you want.\n\nIf language is not available. \n1. Go to your general iPhone settings. \n2. Tap Language & Region to first set your preferred language.",
    androidLanguageIndications: "To change the language in which the text is displayed: \n1. Go to your phone's settings.\n2. Select the language of your choice. \n\nAt the moment the application only supports English and French. ",
    sure_want_sign_out: "Are you sure you want to sign out of {0} ?",
    sign_in: "Sign in",
    disconnection: "Disconnection",
    sign_out: "Sign out",

    posts: "posts",

    map: "Map",
    menu: "Menu",
    contact: "Contact",
    enter_description: "Enter description...",
    add: "Add",
    getting_started: "Getting started",
    categories_are_great: "Categories are an effective way to draw people's attention to important things.",
    what_to_add_on_categories: "Create your first category and add what you would like people to see. For example, advice, products and more.",
    add_category: "Add category",
    try_loading: "Try loading page",
    no_profile_found: "No profile found for that place",
    no_profile_found_explanation: "The place may have changed its name or the page may have been removed.",

    scan_qr_code_to_see_info: "Scan the QR code of a location to access its information.",
    scan_a_qr_code: "Scan a QR Code",

    no_results_found: "No results found",
    email_address_or_username: "Email address or username",
    click_here: "Click here.",

    forgot_password: "Forgot password ?",

    verification_code: "Verification code",
    new_password: "New password",


    translation: "Translation",
    default_language: "Default language",


    // Errors
    not_available_username_error: 'Username is already in use by another account.',
    no_connection_title: 'Network issue',
    no_connection_message: 'Please confirm you have an Internet connection and try again in a moment.',
    empty_confirmation_code: "Please enter the confirmation code to continue.",
    empty_email: "Please enter a valid email address.",
    empty_name: "Please enter a name to continue.",
    empty_password: "Please enter a password with at least 6 characters.",
    email_already_used: "Please enter another email address, this one is already in use by another account.",
    empty_username: "Please enter a username to continue.",
    empty_email_and_username: "Please enter your email address or username to continue.",
    enter_valid_phone_number: "Please enter a valid phone number.",
    username_start_error: "Your username can't start with a period.",
    username_end_error: "Your username can't end with a period.",
    username_length_error: "Uernames can't be more than 26 characters long.",
    invalid_confirmation_code: "Invalid confirmation code.",
    limit_reached: "Attempt limit reached please try again in a moment.",
    pdf_size_error_title: "PDF size exceeds limit.",
    pdf_size_error_message: "The PDF's size exceeds 2MB. Please try lowering its size, for instance if it contains large photos try removing some or reducing their size.",
    category_filled: "Category filled",
    category_filled_error_message: "This category is not empty. To delete this category, please delete its posts first.",
    no_match: "No match",
    qr_code_matching_no_place: "Sorry, this QR code does not matches with any place. Please try again with another QR code.",
    invalid_qr_code: "Invalid QR code",
    only_qr_code_of_places: "Sorry, the application only supports QR codes of places. Please try again with the QR code of a place.",
    incorrect_password: "Incorrect password",
    incorrect_password_description: "The password you entered is incorrect.",

    opening_hours: "Opening hours",
    hours_of_availability: "Hours of availability",
    open_all_day: "Open all day",
    available_all_day: "Available all day",
    close_all_day: "Close all day",
    not_available_that_day: "Not available that day",
    open: "Open",
    available: "Available",
    closed: "Closed",
    not_available: "Not Available",

    preview: "Preview",
    loading: "Loading",
    remove: "Remove",
    remove_all: "Remove all",

    account: "Account",
    see_info_from_places: "See information from places.",
    description_of_what_places_share: "Ideas, stories, opinions, products and anything else places want to share with you.",
    display_language: "Display language",
    change_language_steps: "Steps to change the display language.",
    settings: "Settings",

    essential_info: "Essential information",
    links: 'Links',
    contact_info: "Contact information",
    account_info: "Account information",
    qr_code: "QR code",
    category_types: "Category types",
    calling_codes: "Calling codes",
    countries: "Countries",
    languages: "Languages",
    language: "Language",
    location: "Location",
    category_name: "Category name",
    street: "Street",
    number: "Number",
    email: "Email",
    custom: "Custom",
    link_name: "Link name",
    timetables: "Timetables",
    type: "Type",
    subject: "Subject",
    category_type: "Category type",
    website_link: "Website link",
    link: "Link",
    add_link: "Add link",
    location_in_the_place: "Location in the establishment",
    change_password: "Change password",
    help: "Help",
    yout_categories: "Your categories",
    log_in: "Log In",
    enter_email_or_username_to_login: "Enter your email address or username to log in.",
    create_account: "Create New Account",
    then_choose_password: "Then choose a password.",
    password_changed: "Password changed",
    password_of_was_changed: "The password of {0} has successfully been changed.",
    scanner: "Scanner",
    scan_qr_code_of_place: "'Scan the QR code of the place you are in.'",



    account_type: "Account type",
    select_account_type: "Select your account type.",
    address: "Address",
    address_input_description: "Enter the street address, the city and the country where the location is located.",
    enter_email_or_username: "Enter your email address or username.",
    confirmation_code: "Confirmation code",
    enter_code_sent_to: "Enter the code that was sent to {0}.",
    resend_code: "Resend code.",
    code_sent_to: "Code sent to {0}",
    email_input_description: "Enter a valid email address.",
    name_input_description: "Enter the name of the location.",
    password_input_description: "Create a password.",
    phone_input_description: "Enter the phone number of the location.",
    profile_photo: "Profile photo", // Try to deprecate
    photo: "Photo",
    photo_input_description: "Select a photo for your account or skip.",
    username_input_description: "Choose a username. You will be able to change it later.",
    menu_pdf_and_timetables: "PDF of the menu and its timetables",
    map_pdf: "PDF of the map",
    timetables_of_menu: "Timetables of the menu",
    add_timetables_to_menu: "Add timetables related to the menu. For instance the hours of availability of the room service in an hotel, a restaurant's one, a bar's one and so on.",
    sure_want_remove_map: "Are you sure you want to remove the map ?",
    removing_map_consequences: "Removing the map will permanently delete its PDF.",
    sure_want_remove_menu: "Are you sure you want to remove the menu ?",
    removing_menu_consequences: "Removing the menu will permanently delete its PDF and its timetables if you have added any.",


    choose_library_photo: "Choose photo from library",
    take_photo: "Take a photo",
    delete_category: "Delete category",
    edit_category: "Edit category",
    open_in_maps: "Open in Maps",
    copy: "Copy",
    share: "Share",
    use_qr: "Use QR code",

    main_info: "Main information",
    additional_info: 'Additional information',
    street_address_optional: 'Street address (optional)',
    category: "Category",
    new_category: "New category",
    opened_from: 'Opened from',
    available_from: 'Available from',
    closes_at: 'Closes at',
    available_up_to: 'Available up to',
    special_opening_time: 'Special opening time',
    special_availability_time: "Special availability time",
    new_link: "New Link",
    empty_url: 'Please enter a valid url.',
    link_information: 'Link information',
    additional_language: "Additional language",
    post: "Post",
    modification: "Modification",
    address_optional: "Address (optional)",
    select_category: "Select category",
    profile_buttons: "Profile buttons",
    map_feature_description: "Lets you display a map. For instance, a map of the city or the transports.",
    menu_feature_description: "Lets you display a menu. For instance, the menu of a restaurant or the room service in an hotel.",
    new_item: "New item",
    edit_all: "Edit all",
    new_timetables: 'New timetables',
    subject_of_timetables: "The subject the timetables are related to, for instance : the \"Bar\", the \"Restaurant\" or the \"Room service\".",
    determines_timetables_of_a_service_or_an_activity: "Determines timetables of a service or an activity",
    availability_hours_explanation: "If you set this option to \"true\", timetables determine hours of availability instead of opening hours.",
    delete_timetables: "Delete timetables",
    options: "Options",

    // To translate
    create_new_account: "Create a new account",
    recently_seen: "Recently seen :",
    flash: "Flash",
    usernames_can_only: "Usernames can only use lowercase letters (a-z), numbers, underscores and non consecutive periods.",
    your_qr_code: "Your QR code",
    no_categories_to_display: "This profile has no categories to display for the moment.",
    organize_categories: "Organize categories",
    categories: "Categories",
    custom_category: "Custom category",
    actualized: "Actualized",
    drag_categories_in_order_you_want: "Drag the categories in the order you want.",
    copyright_all_rights_reserved: "Copyright © 2022 AtSight. All rights reserved.",
    sure_want_change_username: "Are you sure you want to change your username ?",
    temporarily_closed: "Temporarily closed",
    temporarily_not_available: "Temporarily not available",
    temporarily_closed_explanation: "Indicates if the place is temporarily closed.",
    temporarily_not_available_explanation: "Indicates if the service or the activity is temporarily unavailable.",
    add_interval: "Add interval",

    // Tabs 
    home: "Home",
    in_the_place: "In the place",
    about: "About",

    nothing_to_display: "There is nothing to display for the momemt.",

    account_deleted: "Account deleted",
    account_successfully_deleted: "Your account and all its information have successfully been deleted.",
    sure_want_delete_account: "Are you sure you want to delete your account ?",
    deleting_account_will: "\nDeleting your account will permantely delete all the information you have provided and all the content you have created. Including your posts, your categories, your websites links, addresses, the things we can find in your establishment or location, your timetables, your contact information, your maps, your menu and all other information. \n\nNote that once your account is deleted, there is no step back.",
    delete_account: "Delete account",
    if_sure_delete_account_enter: "If you are sure you want to delete your account, please enter your username and password and then press continue.",

    delete_modifications: "Supprimer les modifications ?",
    modifications_wont_be_saved: "Les modifications ne seront pas enregistrées",
    default: "Default",
    your_information: "Your information",

    info_on_the_place: "Information about the place",
    enter_a_place: "Enter a Place",
    enter_a_location_or_use_the_camera: "Enter a Location or use the camera",
    please_confirm_that_you_have_an_internet_connection: "Please confirm that you have an internet connection.",
    try_again: "Try again",
    see_timetables: "See timetables",
    atsight_history: "AtSight is a small platform to see information from places. It was created in France, in 2022.",
  
  
    download_qr_code: "Download your QR code",
    place_not_on_atsight_for_the_moment: "Sorry, this place is not on AtSight for the moment.",
 

    how_scanner_works: "Align the QR code in the frame to access the place's information.",
    scanner_not_enabled: "Please allow access to camera to use the scanner.",
    
    
    camera_access: "Camera access",
    atsight_needs_access_to_camera_for_scanner: "AtSight needs access to your camera to enable you to scan qr codes.",
    describe_this_related_item: "Describe this place or service",
    describe_your_post: "Describe your Post",
    providing_location: "Help people find this place or service in your establishment by indicating its location, for instance \"Floor 2\" or \"Rooftop\".",
    name_of_your_category: "Name of your category", 
    add_address: "Add address",
    select_category_or: "Select the category you want this post to be in or",
    create_a_new_one: " create a new one.",
    save: "Save",
    description_too_long: "Description too long", 
    atsight_translates_auto_way_but_you: "AtSight will automatically translate your description for people talking a different language. However if you prefer, you can", // "AtSight will automatically translate your description for people talking a different language. However, if you prefer to have control over the translation in certain languages, you can", 
    provide_your_translation: " provide your translation.",
    select_language_for_translation: "Select a language you want to provide a translation for.",
    see_information_of_place: "See information of this place",
    emojis_forbidden_on_AtSight: "Emojis are forbidden on AtSight",
    if_you_want_to_use_emojis: "If you want to use emojis, use a social media, platforms where people can behave a puerile way.",
    usual_emojis: "🤪🌈❤️👍🐰", 
    see_a_place_information: "See a place's information",


    use_atsight_scanner: "Use AtSight's qr scanner",
    access_information_on_places_by_scanning_qr_codes: "Access information on places by scanning qr codes",
    allow_camera_access: "Allow camera access",
    additional_options: "Additional options",
    analytics: "Analytics",
    impressions: "impressions",
    your_info_has_been_seen_x_times_in_x: "Your information has been viewed {0} times in {1}",
    unique_persons: "Unique persons",
    number_persons_looked_info: "Number of people who viewed your information.",
    spoken_languages: "Spoken languages",
    people_main_language: "Language spoken by these people / number of people speaking this language.",
    activity_times: "Activity times",
    avg_hours_people_view_info: "Hours at which people look at your information on average.",
    no_data_for_this_month: "There is no data to display at the moment",
    no_data_to_view: "No data to view.",
    select_category_for_post: "Select the category you want this Post to be in.", 
    add_phone_number_to_menu: "Add the number that handles your orders so people can order with a click."
  },

















  "fr": {
    pdf: "PDF",
    value: "Valeur",
    description: "Description",
    search: "Rechercher",
    next: "Suivant",
    cancel: "Annuler",
    close: "Fermer",
    edit: "Modifier",
    send: "Envoyer",
    confirm: "Confirmer",
    ok: "OK",
    delete: "Supprimer",
    continue: "Continuer",
    select: "Sélectionner",
    done: "Terminé",
    call: "Appeler",
    send_email: "Envoyer un e-mail",
    see_more: "voir plus",
    translating: "Traduction...",
    show_original: "Afficher l'original",
    show_translation: "Afficher la traduction",
    translate_text: "Traduire le texte",
    edit_the_other_language: "Modifier l'autre langue",
    edit_the_x_other_language: "Modifier les {0} autres langues",
    no_internet_connection: "Pas de connexion Internet",
    profile_not_found: "Profil introuvable",
    copied_to_clipboard: "Copié dans le presse-papiers",
    successfully_sent: "Envoyé avec succès",
    street_address: "Rue",
    city: "Ville",
    country: "Pays",
    code: "Code",
    change_email_address: "Modifier l'adresse e-mail",
    email_address: "Adresse e-mail",
    name: "Nom",
    password: "Mot de passe",
    phone_number: "Numéro de téléphone",
    creating_your_account_can_take_30_seconds: "La création de votre compte peut prendre jusqu'à 30 secondes.",
    username: "Nom d'utilisateur",
    description_optional: "Description (facultatif)",
    email_address_successfully_updated: "Adresse e-mail mise à jour avec succès.",
    phone_number_successfully_updated: "Numéro de téléphone mis à jour avec succès",
    changing_username_will_change_qr_warning: "Changer votre nom d'utilisateur changera votre QR code. Par conséquent, si vous avez placé des codes QR dans votre établissement, vous devrez tous les mettre a jour.",
    select_language: "Sélectionnez la langue",
    write_text: "Écrire du texte.",
    see_how_translation_works: "Découvrez comment fonctionne la traduction.",
    manage_features_you_want_to_add_to_your_profile_descriptive_text: "Sélectionnez les fonctionnalités supplémentaires que vous souhaitez proposer.",
    no_photo: "Aucune photo",
    press_to_edit_photo: "Appuyez pour modifier la photo de votre compte.",
    press_to_switch_pdf: "Appuyez pour changer le PDF.",
    press_to_import_pdf: "Appuyez pour importer un PDF.",
    add_timetables: "Ajouter des horaires",
    no_menu_to_display: "Il n'y a aucun menu à afficher pour le moment.",
    no_map_to_display: "Il n'y a aucune carte à afficher pour le moment.",
    terms: "Conditions d'utilisation",
    privacy: "Politique de confidentialité",
    version: "Version",
    appleLanguageIndications: "Pour modifier la langue dans laquelle le texte est affiché : \n1. Passez à l'écran suivant.\n2. Appuyez sur Langue pour sélectionner la langue de votre choix.\n\nSi la langue n'est pas disponible.\n1. Accédez aux paramètres généraux de votre iPhone.\n2. Appuyez sur « Langue et région » pour définir d'abord votre langue préférée.",
    androidLanguageIndications: "Pour modifier la langue dans laquelle le texte est affiché : \n1. Allez dans les réglages de votre télephone.\n2. Sélectionnez la langue de votre choix. \n\nPour le moment l'application ne supporte que l'Anglais et le Francais.",
    sure_want_sign_out: "Êtes-vous sûr de vouloir vous déconnecter de {0} ?",
    sign_in: "Connexion",
    disconnection: "Déconnexion",
    sign_out: "Se déconnecter",
    posts: "publications",
    map: "Carte",
    menu: "Menu",
    contact: "Contact",
    enter_description: "Saisissez une description...",
    add: "Ajouter",
    getting_started: "Débuter",
    categories_are_great: "Les catégories sont un moyen efficace d'attirer l'attention des gens sur des choses importantes.",
    what_to_add_on_categories: "Créez votre première catégorie et ajoutez-y ce que vous aimeriez que les gens voient. Par exemple, des conseils, des produits et plus encore.",//"Créez votre première catégorie et ajoutez-y ce que vous aimeriez que les gens sachent. Par exemple, vos idées, vos conseils et bien plus encore.",
    add_category: "Ajouter une catégorie",
    try_loading: "Essayer de charger la page",
    no_profile_found: "Aucun profil n'a été trouvé pour ce lieu",
    no_profile_found_explanation: "Le lieu a peut-être changé de nom ou la page a peut-être été supprimée.",
    scan_qr_code_to_see_info: "Scannez le code QR d'un lieu pour accéder à ses informations.",
    scan_a_qr_code: "Scannez un code QR",
    no_results_found: "Aucun résultat trouvé",
    email_address_or_username: "Adresse e-mail ou nom d'utilisateur",
    click_here: "Cliquez ici.",
    forgot_password: "Mot de passe oublié ?",
    verification_code: "Code de vérification",
    new_password: "Nouveau mot de passe",
    translation: "Traduction",
    default_language: "Langue par défaut",
    not_available_username_error: "Le nom d'utilisateur est déjà utilisé par un autre compte.",
    no_connection_title: "Problème de réseau",
    no_connection_message: "Veuillez confirmer que vous disposez d'une connexion Internet et réessayez dans quelques instants.",
    empty_confirmation_code: "Veuillez saisir le code de confirmation pour continuer.",
    empty_email: "Veuillez saisir une adresse e-mail valide.",
    empty_name: "Veuillez saisir un nom pour continuer.",
    empty_password: "Veuillez saisir un mot de passe comportant au moins 6 caractères.",
    email_already_used: "Veuillez saisir une autre adresse e-mail, celle-ci est déjà utilisée par un autre compte.",
    empty_username: "Veuillez saisir un nom d'utilisateur pour continuer.",
    empty_email_and_username: "Veuillez saisir votre adresse e-mail ou votre nom d'utilisateur pour continuer.",
    enter_valid_phone_number: "Veuillez saisir un numéro de téléphone valide.",
    username_start_error: "Votre nom d'utilisateur ne peut pas commencer par un point.",
    username_end_error: "Votre nom d'utilisateur ne peut pas se terminer par un point.",
    username_length_error: "Les noms d'utilisateur ne peuvent pas comporter plus de 26 caractères.",
    invalid_confirmation_code: "Code de confirmation non valide.",
    limit_reached: "La limite de tentatives est atteinte, veuillez réessayer dans quelques instants.",
    pdf_size_error_title: "La taille du PDF dépasse la limite.",
    pdf_size_error_message: "La taille du PDF dépasse 2 Mo. Essayez de réduire sa taille. Par exemple, s'il contient de grandes photos, essayez d'en supprimer certaines ou de réduire leur taille.",
    category_filled: "Catégorie remplie",
    category_filled_error_message: "Cette catégorie n'est pas vide. Pour supprimer cette catégorie, veuillez d'abord supprimer ses publications.",
    no_match: "Aucune correspondance",
    qr_code_matching_no_place: "Désolé, ce code QR ne correspond à aucun lieu. Veuillez réessayer avec un autre code QR.",
    invalid_qr_code: "Code QR non valide",
    only_qr_code_of_places: "Désolé, l'application ne prend en charge que les codes QR des lieux. Veuillez réessayer avec le code QR d'un lieu.",
    incorrect_password: "Mot de passe incorrect",
    incorrect_password_description: "Le mot de passe que vous avez saisi est incorrect.",
    opening_hours: "Horaires d'ouverture",
    hours_of_availability: "Horaires de disponibilité",
    open_all_day: "Ouvert toute la journée",
    available_all_day: "Disponible toute la journée",
    close_all_day: "Fermé toute la journée",
    not_available_that_day: "Non disponible ce jour-là",
    open: "Ouvert",
    available: "Disponible",
    closed: "Fermé",
    not_available: "Non disponible",
    preview: "Aperçu",
    loading: "Chargement",
    remove: "Supprimer",
    remove_all: "Tout supprimer",
    account: "Compte",
    see_info_from_places: "Voir les informations des lieux.",
    description_of_what_places_share: "Des idées, des histoires, des opinions, des produits et tout ce que les lieux veulent partager avec vous.",
    display_language: "Langue d'affichage",
    change_language_steps: "Procédure à suivre pour modifier la langue d'affichage.",
    settings: "Réglages",
    essential_info: "Informations essentielles",
    links: "Liens",
    contact_info: "Informations de contact",
    account_info: "Informations sur le compte",
    qr_code: "Code QR",
    category_types: "Types de catégories",
    calling_codes: "Codes d'appel",
    countries: "Pays",
    languages: "Langues",
    language: "Langage",
    location: "Emplacement",
    category_name: "Nom de la catégorie",
    street: "Rue",
    number: "Numéro",
    email: "E-mail",
    custom: "Personnalisée",
    link_name: "Nom du lien",
    timetables: "Horaires",
    type: "Type",
    subject: "Sujet",
    category_type: "Type de catégorie",
    website_link: "Site Web",
    link: "Lien",
    add_link: "Ajouter un lien",
    location_in_the_place: "Emplacement dans l'établissement",
    change_password: "Changer le mot de passe",
    help: "Aide",
    yout_categories: "Vos catégories",
    log_in: "Se connecter",
    enter_email_or_username_to_login: "Entrez votre adresse e-mail ou votre nom d'utilisateur pour vous connecter.",
    create_account: "Créer un nouveau compte",
    then_choose_password: "Choisissez ensuite un mot de passe.",
    password_changed: "Mot de passe modifié",
    password_of_was_changed: "Le mot de passe de {0} a été modifié avec succès.",
    scanner: "Scanner",
    scan_qr_code_of_place: "Scannez le code QR de l'endroit où vous vous trouvez.",
    account_type: "Type de compte",
    select_account_type: "Sélectionnez votre type de compte.",
    address: "Adresse",
    address_input_description: "Entrez l'adresse, la ville et le pays dans lesquels le lieu est située.",
    enter_email_or_username: "Entrez votre adresse e-mail ou votre nom d'utilisateur.",
    confirmation_code: "Code de confirmation",
    enter_code_sent_to: "Entrez le code qui a été envoyé à {0}.",
    resend_code: "Renvoyez le code.",
    code_sent_to: "Code envoyé à {0}",
    email_input_description: "Entrez une adresse e-mail valide.",
    name_input_description: "Entrez le nom de l'emplacement.",
    password_input_description: "Créez un mot de passe.",
    phone_input_description: "Entrez le numéro de téléphone du lieu.",
    profile_photo: "Photo de profil", // Try to deprecate
    photo: "Photo",
    photo_input_description: "Sélectionnez une photo pour votre compte ou ignorez.",
    username_input_description: "Choisissez un nom d'utilisateur. Vous pourrez le modifier ultieurement.",
    menu_pdf_and_timetables: "PDF du menu et ses horaires",
    map_pdf: "PDF de la carte",
    timetables_of_menu: "Horaires du menu",
    add_timetables_to_menu: "Ajoutez des horaires liés au menu. Par exemple, les heures de disponibilité du room service dans un hôtel, d'un restaurant, d'un bar, etc.",
    sure_want_remove_map: "Êtes-vous sûr de vouloir supprimer votre carte ?",
    removing_map_consequences: "La suppression de la carte entraînera la suppression définitive de son PDF.",
    sure_want_remove_menu: "Êtes-vous sûr de vouloir supprimer le menu ?",
    removing_menu_consequences: "La suppression de votre menu supprimera définitivement son PDF et ses horaires si vous en aviez ajouté.",
    choose_library_photo: "Choisir une photo dans la bibliothèque",
    take_photo: "Prendre une photo",
    delete_category: "Supprimer la catégorie",
    edit_category: "Modifier la catégorie",
    open_in_maps: "Ouvrir dans Maps",
    copy: "Copier",
    share: "Partager",
    use_qr: "Utiliser le code QR",

    main_info: "Informations principales",
    additional_info: "Informations supplémentaires",
    street_address_optional: "Rue (facultatif)",
    category: "Catégorie",
    new_category: "Nouvelle catégorie",
    opened_from: "Ouvert à partir de",
    available_from: "Disponible à partir de",
    closes_at: "Ferme à",
    available_up_to: "Disponible jusqu'à",
    special_opening_time: "Horaires d'ouverture spéciaux",
    special_availability_time: "Période de disponibilité spéciale",
    new_link: "Nouveau lien",
    empty_url: "Veuillez saisir un lien valide.",
    link_information: "Informations sur le lien",
    additional_language: "Langue supplémentaire",
    post: "Publication",
    modification: "Modification",
    address_optional: "Adresse (facultatif)",
    select_category: "Choisissez une catégorie",
    profile_buttons: "Boutons du profil",
    map_feature_description: "Vous permet d'afficher une carte. Par exemple, un plan de la ville ou des transports.",
    menu_feature_description: "Vous permet d'afficher un menu. Par exemple, le menu d'un restaurant ou le « room service » d'un hôtel.",
    new_item: "Nouvel élément",
    edit_all: "Tout modifier",
    new_timetables: "Nouveaux horaires",
    subject_of_timetables: "Le sujet auquel les horaires sont liés, par exemple : le « Bar », le « Restaurant » ou le « Room service ».",
    determines_timetables_of_a_service_or_an_activity: "Détermine les horaires d'un service ou d'une activité",
    availability_hours_explanation: "Si vous définissez cette option sur « vrai », les horaires déterminent des heures de disponibilité au lieu que des heures d'ouverture.",
    delete_timetables: "Supprimer les horaires",
    options: "Options",

    create_new_account: "Créer un nouveau compte",
    recently_seen: "Vu récemment :",
    flash: "Flash",
    usernames_can_only: "Les noms d'utilisateur ne peuvent utiliser que des lettres minuscules (a-z), des chiffres, des traits de soulignement et des points non consécutifs.",
    your_qr_code: "Votre QR code",
    no_categories_to_display: "Ce profil n'a pas de catégories à afficher pour le moment.",
    organize_categories: "Organiser les catégories",
    categories: "Catégories",
    custom_category: "Catégorie personnalisée",
    actualized: "Actualisé",
    drag_categories_in_order_you_want: "Faites glisser les catégories dans l'ordre que vous souhaitez.",
    copyright_all_rights_reserved: "Copyright © 2022 AtSight. Tous droits réservés.",
    sure_want_change_username: "Êtes-vous sûr de vouloir changer votre nom d'utilisateur ?",
    temporarily_closed: "Temporairement fermé",
    temporarily_not_available: "Temporairement indisponible",
    temporarily_closed_explanation: "Indique si le lieu est temporairement fermé.",
    temporarily_not_available_explanation: "Indique si le service ou l'activité est temporairement indisponible.",
    add_interval: "Ajouter un intervalle",

    // Tabs 
    home: "Accueil",
    in_the_place: "Dans le lieu",
    about: "À propos",

    nothing_to_display: "Il n'y a rien à afficher pour le moment.",


    account_deleted: "Compte supprimé",
    account_successfully_deleted: "Votre compte et toutes ses informations ont été supprimés avec succès.",
    sure_want_delete_account: "Êtes-vous sûr de vouloir supprimer votre compte ?",
    deleting_account_will: "\nLa suppression de votre compte supprimera définitivement toutes les informations que vous avez fournies et tout le contenu que vous avez créé. Y compris vos publications, catégories, liens de sites Web, adresses, éléments que nous pouvons trouver dans votre établissement ou emplacement, heures d'ouverture, coordonnées, cartes, menu et toute autre information. \n\nNotez qu'une fois votre compte supprimé, il n'y a pas de retour en arrière.",
    delete_account: "Supprimer le compte",
    if_sure_delete_account_enter: "Si vous êtes sûr de vouloir supprimer votre compte, veuillez saisir votre nom d'utilisateur et votre mot de passe, puis appuyez sur continuer.",

    default: "Défaut",
    your_information: "Vos informations",

    info_on_the_place: "Informations sur le lieu",
    enter_a_place: "Saisissez un Lieu",
    enter_a_location_or_use_the_camera: "Saisissez un Lieu ou utilisez la caméra",
    please_confirm_that_you_have_an_internet_connection: "Veuillez confirmer que vous disposez d'une connexion Internet.",
    try_again: "Réessayer",
    see_timetables: "Voir les horaires",
    atsight_history: "AtSight est une petite plate-forme pour voir des informations sur des lieux. Elle a été créé en France, en 2022.",
  

    download_qr_code: "Télécharger votre code QR", 
    place_not_on_atsight_for_the_moment: "Désolé, ce lieu n'est pas sur AtSight pour le moment.",
 
    
    how_scanner_works: "Alignez le QR code dans le cadre pour accéder aux informations du lieu.",
    scanner_not_enabled: "Veuillez autoriser l'accès à l'appareil photo pour utiliser le scanner.",
    
    camera_access: "Accès à la caméra",
    atsight_needs_access_to_camera_for_scanner: "AtSight a besoin d'accéder à votre caméra pour vous permettre de scanner des codes qr.",
    describe_this_related_item: "Décrivez ce lieu ou ce service",
    describe_your_post: "Décrivez votre Publication",
    providing_location: "Aidez les gens à trouver ce lieu ou ce service dans votre établissement en indiquant son emplacement, par exemple \"Étage 2\" ou \"Rooftop\".",
    name_of_your_category: "Nom de votre catégorie", 
    add_address: "Ajoutez l'adresse",
    select_category_or: "Sélectionner la catégorie dans laquelle vous souhaitez que cette publication soit ou",
    create_a_new_one: " créez en une nouvelle.",
    save: "Enregistrer",
    description_too_long: "Description trop longue", 
    atsight_translates_auto_way_but_you: "AtSight traduira automatiquement votre description pour les personnes parlant une autre langue. Cependant si vous préférez, vous pouvez", 
    provide_your_translation: " fournir votre traduction.",
    select_language_for_translation: "Sélectionnez la langue pour laquelle vous souhaitez fournir une traduction.",
    see_information_of_place: "Voir les informations de ce lieu",
    emojis_forbidden_on_AtSight: "Les emojis sont interdits sur AtSight",
    if_you_want_to_use_emojis: "Si vous voulez utiliser des emojis, utilisez un réseau social, des plateformes où les gens peuvent se comporter de manière puérile.", 
    usual_emojis: "🤪🌈❤️👍🐰", 
    see_a_place_information: "Voir les informations d'un lieu",

    access_information_on_places_by_scanning_qr_codes: "Accédez à des informations sur des lieux en scannant des codes qr",
    allow_camera_access: "Autoriser l'accès à la caméra",
    additional_options: "Options additionnelles",
    analytics: "Statistiques", 
    impressions: "impressions",
    your_info_has_been_seen_x_times_in_x: "Vos informations ont été consultées {0} fois en {1}",
    unique_persons: "Personnes uniques",
    number_persons_looked_info: "Nombre de personnes qui ont vues vos informations.", 
    spoken_languages: "Langues parlées",
    people_main_language: "Langue parlée par ces personnes / nombre de personnes parlant cette langue",
    activity_times: "Temps d'activité", 
    avg_hours_people_view_info: "Heures auxquelles les gens regardent vos informations en moyenne.",
    no_data_for_this_month: "Il n'y a pas de données à afficher pour le moment",
    no_data_to_view: "Aucune donnée à afficher.",
    select_category_for_post: "Sélectionner la catégorie dans laquelle vous souhaitez que cette Publication soit.",
    add_phone_number_to_menu: "Ajoutez le numéro qui traite vos commandes pour permettre aux gens de commander en un click."
  },
})


export default localization